### ISSUE TITLE
Improved Better Skulls

### ISSUE THREAD

**Issue by Darkloke** [Tyler799/Morrowind-2019#101]
This mod also has atlased version with different set of textures, so need some advice which one to select.

Also esp-file non localized, but i suppose its safe to ignore it.

In addition i would like to suggest an alternative mod:
http://tesall.ru/files/file/1633-bone-items/

**Comment by Tyler799** [comment]
The Atlased version is in addition to IBS, not as an alternate. They can be used together. 

AS for what version, I'd suggest option 01 - Improved Better Skulls Textures.

I'll add that info to the guide.

**Comment by Darkloke** [comment]
The only thing i would add - that Bone Items contains some meshes not included in Improved Better Skulls. So in case u prefer IBS u still could install Bone Items to add missing items.
