### ISSUE TITLE
R-Zero's Random Retextures (and Replacers)

### ISSUE THREAD

**Issue by Darkloke** [Tyler799/Morrowind-2019#103]
Now that more exist, I recommend installing all of them.

Actually no.

Dwemer Coin textures are already better in Full Dwemer Retexture (512 vs 256 and 512 vs 128)
misc_skull10.nif from Improved Better Skulls is already better too.

So i would say get all except Dwemer Coin and Servant's Skull.

**Comment by Tyler799** [comment]
You're correct, I've removed those now.
