### ISSUE TITLE
Ghostnull's Silverware Enhancer

### ISSUE THREAD

**Issue by Darkloke** [Tyler799/Morrowind-2019#104]
I suppose it could be substituted now with Silverware Repolished
https://www.nexusmods.com/morrowind/mods/46385

**Comment by Tyler799** [comment]
To be honest, the images on the mod page for Ghostnull's are a little far, hard to tell what's better from there.

Need some close-range screenshots to compare the two, see what's better. If very similar, might just add as alternate.

**Comment by Tyler799** [comment]
As an aside:

>Pherim's has better meshes, but the textures are pretty bad and the optional bump-mapped version looks like plastic. Ghostnull's has terrible, subsurfaced vanilla meshes, but okayish textures with nice reflection maps.

Also, Pherim's at Atlased. If they weren't, we could get the both of best worlds and use Pherim's meshes and Ghostnull's textures. But oh well.
