### ISSUE TITLE
Potions & Scrolls icons

### ISSUE THREAD

**Issue by Darkloke** [Tyler799/Morrowind-2019#108]
I think these mods are undeservedly forgotten:
http://mw.modhistory.com/download-35-2339

Potions has an alternative:
https://www.nexusmods.com/morrowind/mods/44374

**Comment by Tyler799** [comment]
Labeled Potions can't be used directly as it forwards changes from the Morrowind Patch Project v1.6.6. What all does the ESP do? Find out, and if it's possible I can just add it as an alternate.

And I'm assuming "Potions and Scrolls" would be a load-after to Ultimate Icon Replacer? No problem with doing that, just want to be sure.

**Comment by Darkloke** [comment]
Yeah, they should be installed after UIP and an ESP file is necessary in this case since it maps unique icon to every potion/scroll in the game - this cannot be done as plain replacer w/o esp-file.

**Comment by Tyler799** [comment]
Then I'll need to pass on the first mod, but Potions and Scrolls I'll go ahead and add as an alternate.

**Comment by Darkloke** [comment]
>> Alternatives, for potions you may want [Potions and Scrolls]

For potions AND scrolls would be more correct i suppose.

**Comment by Tyler799** [comment]
Whoops, yeah. Thanks.
