### ISSUE TITLE
MOP and Project Atlas order

### ISSUE THREAD

**Issue by Remiros** [Tyler799/Morrowind-2019#111]
MOP and Project Atlas should be installed before any other mesh improvements.

**Comment by Tyler799** [comment]
In the future, please provide a source. Like, the description from a mod page. Or a quote from an author.

Like this:

>It is highly recommended that you use MOP together with Project Atlas. Make sure to install to install Project Atlas **after** MOP.

(From the MOP description)

Something, anything to go off of why the mods need to be re-ordered.

However, in this case the reasoning seems fairly clear. 

I've gone ahead and re-ordered them.

**Comment by Tyler799** [comment]
And thanks, of course. :)
