### ISSUE TITLE
base_anim_female.1st.nif

### ISSUE THREAD

**Issue by Gamertagls** [Tyler799/Morrowind-2019#113]
Did everything up until the Cleaning mods section and game was running well with no error messages. Then I only cleaned the mods mentioned, minus VoicedVivec.ESP because it was taking so long for some reason, then tried to play the game and got this message before the main menu, "Only one root object allowed on file "base_anim_female.1st.nif". 
Make sure the object was exported without cameras." Then after the opening scinamatic, the game crashes without any message popping up.
Any help appreciated.

**Comment by Tyler799** [comment]
Yeah, I heard about this before. It has to do with the INI edits in the guide. I'll remove them from the guide, and I'd suggest you try going back to the vanilla INIs.

**Comment by Gamertagls** [comment]
Sorry if I missed anything I'm newer to modding. I download a fresh .ini from Nexus mods and switched it with the one that was in my folder, but after switching over the BSA's I still couldn't figure out a way to stop the error.

**Comment by Tyler799** [comment]
You reverted the ini inside the MO2 profile folder? This folder: 

![morrowindini](https://user-images.githubusercontent.com/2636178/59155085-44e56300-8a3e-11e9-9613-5a25e418a73e.png)

**Comment by Gamertagls** [comment]
Yes, I just did and that fixed it, I don't know why that happened because I didn't think I messed with my .ini but I guess I must have done something with it.
Thank you for your help and for this guide as a whole. A lot of work went into this I can tell.

**Comment by Tyler799** [comment]
Thanks. And to be 100% clear - the INI changes that caused this issue were the ones that were under "Tweaks" using mINI for weather stuff?

That's the section I removed, hopefully should fix it.
