### ISSUE TITLE
HiRes Scrib by Flash3113 not available anymore

### ISSUE THREAD

**Issue by Bobb12341** [Tyler799/Morrowind-2019#115]
Per the guide under Creature Replacers:
"HiRes Scrib - I use the bright version."

This links to the following page on nexus mods:
https://www.nexusmods.com/morrowind/mods/43352/?

However, as of June 13, 2019, this mod is hidden and cannot be accessed.

**Comment by Tyler799** [comment]
Apologies for the late reply, I'll strip it from the guide.
