### ISSUE TITLE
Mlox and Wrye Bash

### ISSUE THREAD

**Issue by BlaiseDebeste** [Tyler799/Morrowind-2019#117]
After downloading Mod Organizer 2, as the guide says, I went to and Mlox and Wrye Bash to the list. Unfortunately, I can't find how to do that, neither through trial and error nor through the Internets.
Thoughts?

**Comment by Tyler799** [comment]
> I went to and Mlox and Wrye Bash to the list

I think you missed a word there.

I'll be honest, I have no idea what you're saying.

Wyre mash is here: https://www.nexusmods.com/morrowind/mods/45439/

Mlox is here: https://github.com/mlox/mlox/releases/

I linked them in the guide.

And neither of them are installed like a normal mods, they're executables. You add them to the MO2 executable list.

If you want to know how to do that, watch any of the great MO1 or MO2 tutorials or ask on the MO2 discord, or the /r/skyrimmods discord. 

But here's a picture if it helps. https://imgur.com/VRbC5ID

**Comment by BlaiseDebeste** [comment]
Thank you for the quick reply. I'm not sure where that menu comes from, though, although I do have an awful memory.
I'll look into those sources you mentioned. Thanks again for doing all this!

**Comment by Tyler799** [comment]
It comes from here: https://imgur.com/m0Bm6KD

**Comment by BlaiseDebeste** [comment]
What I meant was, I don't know where that GUI comes from- Mlox, Mod Organizer 2, or Wyre Bash, or something else.

**Comment by Tyler799** [comment]
Mod organizer 2.

**Comment by BlaiseDebeste** [comment]
Mod Organizer 2? It looked nothing like that for me. Odd.

**Comment by Tyler799** [comment]
I'm using a dark theme.

**Comment by BlaiseDebeste** [comment]
Oh, dear, Sorry. All right. Now I think I know what to do now. Thanks again.
