### ISSUE TITLE
mlox has updated

### ISSUE THREAD

**Issue by kyleshrader** [Tyler799/Morrowind-2019#129]
The guide describes an issue with mlox 1.0, as of aug 12th. There were two updates, aug 17th and 18th. Did these resolve the issues you experienced?

**Comment by jimfcarroll** [comment]
In case it matters, I noticed this and have been using mlox 1.0 without problems following the guide. I'm not sure what the author's original problems were.

**Comment by Tyler799** [comment]
Closed, fixed.
