### ISSUE TITLE
Download for BetterClothesBloodMoonPlus not working

### ISSUE THREAD

**Issue by xana43** [Tyler799/Morrowind-2019#13]
I understand that you know that fliggerty is down, and it's been down for a while now. I tried to find the download link for the mod on the wayback machine, but there was no archive of it at all. So I was wondering if you could link another BetterClothesBloodMoonPlus 1.5 in the guide

**Comment by Tyler799** [comment]
Wayback works fine: https://web.archive.org/web/20161103154305/http://download.fliggerty.com/file.php?id=804
