### ISSUE TITLE
Bundled complete install

### ISSUE THREAD

**Issue by jimfcarroll** [Tyler799/Morrowind-2019#132]
I have an MO2 complete install I was thinking of sharing (probably torrent since I doubt anyone would host it as a free download). It has all of the options with notes. It would make installing a "Thastus" profile fairly easy and much quicker. I was thinking people could download a (massive) 7z file and expand it directly into your MO2 install and all of the mods would be there with notes so following the guide would be just selecting options. For example:

![Capture](https://user-images.githubusercontent.com/372696/69800688-c3c48880-11a3-11ea-8b1f-f7ffe242aaf3.PNG)

Does anything think this might be useful?

**Comment by Tyler799** [comment]
No. That is considered mod piracy. Mod authors did not give their permission for those mods to be distributed elsewhere.

**Comment by jimfcarroll** [comment]
Makes sense. Thanks.
