### ISSUE TITLE
"WIP Smooth Correct UV Rocks" Link Broken

### ISSUE THREAD

**Issue by MED-Projects** [Tyler799/Morrowind-2019#137]
Just a broken link, does not lead anywhere. 

http://forums.bethsoft.com/topic/1514660-alternatives-to-on-the-rocks/?p=23908143

**Comment by Tyler799** [comment]
Done, using the one from [here](https://www.nexusmods.com/morrowind/mods/44321?tab=files). Honestly no idea if it's the right option, kinda not maintaining this anymore, was hoping other people would make pull requests to fix some of this.
