### ISSUE TITLE
Standard version of Dunmeri Urns - Aestetika of Vvardenfell causes CTD

### ISSUE THREAD

**Issue by Tiber-Septim** [Tyler799/Morrowind-2019#15]
The non bump mapped version of Dunmeri Urns - Aestetika is broken and will crash the game when approaching certain cells. (I initially encountered it while moving towards the Vivec boatmaster.) Amusingly, Thastus, reddit turned up an old post of you having trouble with this and also the solution:

https://www.reddit.com/r/Morrowind/comments/55o4ig/i_followed_the_step_guide_but_im_getting_a_few/

I can confirm that replacing with the bump mapped version of the mod fixes the error. The guide could either just blanket tell people to use that edition, or else offer the other suggested fixes. (Not confirmed by me as solutions, though.)

**Comment by Tyler799** [comment]
Thanks. I'm using the bump-mapped version so I wasn't experiencing this. I'll fix this ASAP.

**Comment by Tyler799** [comment]
Fixed and closed.
