### ISSUE TITLE
Tamriel Rebuilt grass generation for MGE options

### ISSUE THREAD

**Issue by Tiber-Septim** [Tyler799/Morrowind-2019#16]
The guide's current grass generation protocol leaves TR lands without groundcover; I have done research on the new Old Ebonheart update and can only find a mod that works with Vurt's groundcover:

https://www.nexusmods.com/morrowind/mods/45973?tab=description

I've confirmed personally that this is a working option, if you're willing to also use Vurt's only in Vvardenfell. That could be offered as the intermediate solution while I investigate the possibility of getting the, in my opinion, superior Ozzy's grass working.

**Comment by Tyler799** [comment]
So to be clear, would your suggestion be to put this mod directly after Vurt's groundcover as an option for those with TR? 

Also, Vurts groundcover is not a non-changable component. If you have other options, I'd be glad to hear them.

**Comment by Tiber-Septim** [comment]
Sorry, I should have used the mod name instead: Ozzy is the author of the Grass Mod Combined you've rightly put ahead of Vurt's in the guide. Vurt's is perfectly fine as a secondary option, but I'm hoping to find some way to make TR grass work with GMC. I'll update you if I do.

Until then, yeah, all people need to do is install this mod and then follow the same protocol for grass generation ESPs. TR_Grass_Gen should be left unchecked in MO and but ticked for MGE. Even though it's "only compatible with Vurt's", I did run it with the Azura's Coast and Sheogorath mod with no trouble as that mod of course doesn't interfere.

So, ultimately, there are three possible grass ESP setups here:

- AC&S + GMC + Ashlands/Reeds/Corals: no TR grass
- AC&S + All Vurt's plugins: no TR grass
- AC&S + All Vurt's + TR Grass Gen: All of VVardenfell plus TR grass

**Comment by Tyler799** [comment]
Alright, then I think the changes I put in should be good. Let me know (or make a pull request) if you feel they're not satisfactory.
