### ISSUE TITLE
Link to Antares' Big Mod is outdated, Uvirith's Legacy lacks a TR Patch

### ISSUE THREAD

**Issue by Seeesq** [Tyler799/Morrowind-2019#18]
https://www.nexusmods.com/morrowind/mods/44656/?

(sorry if this isnt the right way to do this ive never used git hub)

also the version of antares' big mod linked is (slightly) out of date, new versions up here http://arcimaestroantares.webs.com/antaresbigmod.htm

**Comment by Tyler799** [comment]
Thanks, added!

As for contributing, one way would be by opening the .md file here on github (not downloading it) and then submitting the changed copy as a "pull request" with its title/description being what changed.

Or, you can make an *issue* that says what's wrong, like "Link to Antares' Big Mod is incorrect" and "Uvirith's legacy lacks a TR patch". Keeping them separate from each other is a little helpful for organization.
