### ISSUE TITLE
Morrowind Freezes After Pressing Play in MO2

### ISSUE THREAD

**Issue by Gamertagls** [Tyler799/Morrowind-2019#21]
Whenever I try and run Morrowind after completing the Baseline Installation and Boilerplate part of the guide a small black window appears on my screen and freezes forcing me to close it with the task manager. Only installed to the end to the Baseline Installation and Boilerplate tab. Morrowind.exe works but with no mods. Tried uninstalling and re-installing with the same problem.

**Comment by Tyler799** [comment]
That's odd, I never got an e-mail for the original issue. I noticed you've closed this issue, did you end up finding the cause?

**Comment by theyellingmute** [comment]
so i had this same issue, try updating Mod Organizer 2 v2.2.0beta8 from their github. It helped with my issue which was exactly as you described.
