### ISSUE TITLE
mash won't run from inside MO2

### ISSUE THREAD

**Issue by Weaver23PH** [Tyler799/Morrowind-2019#22]
22:03:24.736 [D] setting file times on esps
22:03:25.067 [D] Load Mechanism: Mod Organizer
22:03:25.492 [D] Updating VFS mappings...
22:03:25.966 [D] VFS mappings updated <linked 256 dirs, 3 files>
22:03:25.970 [D] Spawning direct process < "C:/Morrowind/Mopy/mash64.exe" , "" , "C:/Morrowind/Mod Organizer 2 (Archive)/profiles/Default" >
22:03:25.971 [D] Creating process hooked: < "\"C:\\Morrowind\\Mopy\\mash64.exe\"\u0000\u0000" >
22:03:26.048 [D] Waiting for spawned process completion : mash64.exe (10416)
22:03:27.688 [D] Waiting for process completion successfull
22:03:27.736 [D] removing loadorder.txt
22:03:29.604 [D] C:\Morrowind\Mod Organizer 2 (Archive)\profiles\Default\loadorder.txt saved
22:03:29.607 [D] C:\Morrowind\Mod Organizer 2 (Archive)\profiles\Default\lockedorder.txt saved
22:03:29.608 [D] setting file times on esps

**Comment by Tyler799** [comment]
Sorry for the late reply. Ensure you're on the latest MO2 (2.2.0 Beta 8 at the time of writing). As well, make sure you are on the latest version of Windows. There was an issue with MO2 running on older copies of Windows 10 that cause the virtual filesystem to fail and Wyre won't launch properly/at all. It launches fine if you're on the latest windows. You might need to get the update tool from MS's website.
