### ISSUE TITLE
graphic herbalism addons cause issues loading in

### ISSUE THREAD

**Issue by theyellingmute** [Tyler799/Morrowind-2019#23]
when using the Tamriel Data Patch you mentioned in "Major Mods to be aware of" you mentioned you needed a patch which linked to Graphic Herbalism Addons. but if you try using this it refers to an something that is no longer used because the tamriel data file changed at some point. maybe i missed something but the core file still works fine with tamriel rebuilt  but when i try using that addon mod it mentions something along the lines of dummy files couldnt be found for some scripts.

my game is working fine without the addon (so far) but it is still very early in the game so im not sure if i might eventually run into issues. just posting this as maybe i just overlooked something or they are no longer compatible for some reason and can let other people know if they are having issues.

**Comment by Tyler799** [comment]
To be honest, I have never used Tamriel Reborn. It might be easier to ask on the Morrowind modding discord about it, or if there's a Tamriel reborn subreddit/discord that'd be even better.

**Comment by Tyler799** [comment]
Graphic Herbalism has been superseded by Happy Harvesting for MWSE (which doesn't make visual changes like GH does), and will be replaced by a GH re-made in LUA for MWSE later. I'm closing this issue for now because it'll be irrelevant fairly soon. Hope that's alright. I've not updated the guide because until the new GH comes out, I don't want to swap it in for HH.

**Comment by Tyler799** [comment]
Actually: Something else may be to blame in your case. If you installed the **Tamriel Data** addon but then activated the **Tamriel Rebuilt addon from the Graphic Herbalism download** (which is, indeed, completely outdated), then you'd have this issue.

**Comment by theyellingmute** [comment]
yeah thats what i meant. sorry if it wasnt clear but that one specifically was the issue. the other core mods worked without issue
