### ISSUE TITLE
Swap Graphic Herbalism Out for GH-Lua when it releases

### ISSUE THREAD

**Issue by Tyler799** [Tyler799/Morrowind-2019#26]
GH is a bit of a mess, and has been replaced with [Happy Harvesting](https://www.nexusmods.com/morrowind/mods/45627). However, HH doesn't provide the nice visual changes that GH does, so I'm waiting for Stuporstar to release the GH made in MWSE with LUA. 

Once it releases, I'll swap it in and remove all references to Graphic Herbalism and related patches.

**Comment by yooksi** [comment]
It would seem it was just [released](https://github.com/Greatness7/graphicHerbalism/blob/master/main.lua) today. Abot is reporting a 10-20% improve in performance over the old plugin version.
