### ISSUE TITLE
Adding Weapon Sheathing (Clipping/compatibility?)

### ISSUE THREAD

**Issue by Tyler799** [Tyler799/Morrowind-2019#28]
This mod: https://www.nexusmods.com/morrowind/mods/46069

Considering adding it. However, concerned about the compatibility with: 

* Better bodies (the default)
* Robert's bodies
* New Beast Bodies - Clean Version
* Wey's Argonians (the default)
* Improved Argonians
* Better Morrowind Armor
* Less Bulky Pauldrons

Testing and help with this is greatly appreciated, though I'll do some of my own.

**Comment by NullCascade** [comment]
It should be compatible with those. It updates meshes with new mwse-lua scripting, so it should be compatible with all other body mods. Notice that the mesh contained is `xbase_anim_sh.nif`. All the other meshes also end in this `_sh.nif` extension, which the mod loads and then patches the derived mesh with.

**Comment by DaelosTheCat** [comment]
I've tested this and haven't noticed any incompatibilities (besides some minor clipping (to be expected)).
