### ISSUE TITLE
Optimization concerns with Vurt's Trees

### ISSUE THREAD

**Issue by yooksi** [Tyler799/Morrowind-2019#31]
From testing the new assets in this guide, I've found that Vurt's trees in particular cause a medium to high performance hit in some areas of the world. They are also not the best visual options in my opinion, but that aside, they are not compatible with MOP and are also not recommended by some of the big player on MW Discord.

A note from *Morrowind Optimization Project* state that:

> This will overwrite meshes you already have installed. Do NOT use this with Vurt's Trees.

I've started a short discussion about which trees are best for an optimized MW setup and I was told this:

> Vurt's trees are horribly optimized, I go with Rem for Ascadian Isles, Melchior's West Gash trees (vanilla friendly as well). Grab all the trees in MOP, Rem's Ascadian isles, MD's West Gash and that should be optimized enough without using vurt.

**Comment by Tyler799** [comment]
For reference:

This is in the Nature Texture & Mesh Replacers section.

It is suggested to

* remove [Vurts Leafy West Gash II](https://www.nexusmods.com/morrowind/mods/37400)
* leave up the alternative, [Vanilla-friendly West Gash Tree Replacer](https://www.nexusmods.com/morrowind/mods/44173).
* As well, [Connary's West Gash](http://www.fullrest.ru/files/connaryswestgash) would likely not be needed, but I could do a file-by-file comparison to see if it is completely over-written.
* Swap out with [Vurts Ascadian Isles Trees Replacer II](https://www.nexusmods.com/morrowind/mods/37249/) with [Remiros' Ascadian Isles Trees 2](https://www.nexusmods.com/morrowind/mods/45779)
* Leave Vurt's Solsteim, Grazeland, Bitter Coast and Mournhold trees, or find some alternative?

**Comment by Tyler799** [comment]
Closed as the changes possible to make have been made.
