### ISSUE TITLE
Consider applying a commit style 

### ISSUE THREAD

**Issue by yooksi** [Tyler799/Morrowind-2019#38]
From my EU4 [mod project](https://github.com/yooksi/eu4-EVE/wiki/Commit-Style):

>  Custom commit style provides standardized workflow, improved readability of commit history and fun! Unlike the standard commit convention that uses category keywords to help recognize relevant commit, we're using emojis. Using emojis on commit messages provides an easier way of identifying the purpose or intention of a commit with only looking at the emojis used.

Example of how I used it there:

- :arrow_right: :heavy_plus_sign: `Migrating code to a new file`  
- :children_crossing: :star: `Implement new user feature `

**Comment by Tyler799** [comment]
For now I'm going to go against this. If there's a lot of support for this idea from others, I'll reconsider.
