### ISSUE TITLE
Consider swapping (or just overwriting) Tyddy's landscape with Vanilla Land

### ISSUE THREAD

**Issue by Tyler799** [Tyler799/Morrowind-2019#4]
Please leave your thoughts, or screenshot comparisons here.

**Comment by Tyler799** [comment]
If I loaded Vanilla Land after Tyddy's, there'd be 50 non-conflicted files.

**Comment by Tyler799** [comment]
Closed. I think I'll just have both as an option, or load VL after Tyddys. If anyone has final thoughts on this matter, feel free to look at the section in question and put your suggestion here.

**Comment by Darkloke** [comment]
"There's a lot of overlap between these two mods, but 50 textures or so from Tyddy's aren't covered by Vanilla Land."

Hm, actually as i see Vanilla Land covers ALL textures from Tyddy's landscape (assuming u installed HQ+UHQ Packs, BUT Tyddy's UHQ pack offers textures in 4k resolution vs 2k from Vanilla.

So i suppose its enough to have Vanilla Land + UHQ Tyddy's landscape over.
