### ISSUE TITLE
Add UI Expansion

### ISSUE THREAD

**Issue by yooksi** [Tyler799/Morrowind-2019#41]
An user interface mod that expands UI functionality with searching, filtering, and more visual feedback. It was requested on our channel and recommended by Corsair.

![UI Expansion](https://staticdelivery.nexusmods.com/mods/100/images/thumbnails/46071/46071-1538420403-1167645233.jpeg)

**Comment by Tyler799** [comment]
I like it. Assuming it works fine with mods that modify/add dialogue and the rest, seems like a very solid addition to me.

**Comment by Tyler799** [comment]
Added, thanks!

**Comment by yooksi** [comment]
This issue needs to be properly closed with a commit reference.
