### ISSUE TITLE
Adding a MWSE Section 

### ISSUE THREAD

**Issue by SumSineRegno** [Tyler799/Morrowind-2019#43]
It has occurred to me that if this guide is going to include MWSE mods that it should have a section of its own. Since it would allow you to separate out these mods from the others and give explanation on how to use them, install MWSE (which is rather easy), and other such things. This would of course avoid people installing these mods without MWSE and then getting confused when they do not work. 

However, discussing this in the discord it has been brought up that it might also be confusing in another regard due to people being confused about these mods not being with the other of their kind. So alternatively, you could have a section on MWSE at the beginning in boilerplate or just a small standalone section explaining the gist of what MWSE is and how it works, and then saying that MWSE mods will be noted as such, and have the mods be in the relevant section. Or do a little of both, and have a section explaining MWSE, put the mods in the section they belong and then have a section for optional MWSE mods or a subsection in optional.

These are just my thoughts on this matter. Hopefully they are of help. And that my language is not too opaque or obtuse (though nothing editing this won't fix).

**Comment by yooksi** [comment]
@SumSineRegno Thank you for making your suggestion in the issue tracker! :bowtie:
 
> Alternatively, you could have a section on MWSE at the beginning in boilerplate or just a small standalone section explaining the gist of what MWSE is and how it works, and then saying that MWSE mods will be noted as such, and have the mods be in the relevant section

I think this is a really good idea, and I was kind of surprised that we already didn't have a short paragraph explaining what MWSE is and how install such mods. Definitely need to add that, as well as note all MWSE mods with an icon of sort so that they can be easily seen in the guide (and avoided if the user is not using the nightly build).

**Comment by SumSineRegno** [comment]
> @SumSineRegno Thank you for making your suggestion in the issue tracker! :bowtie:
> 
> > Alternatively, you could have a section on MWSE at the beginning in boilerplate or just a small standalone section explaining the gist of what MWSE is and how it works, and then saying that MWSE mods will be noted as such, and have the mods be in the relevant section
> 
> I think this is a really good idea, and I was kind of surprised that we already didn't have a short paragraph explaining what MWSE is and how install such mods. Definitely need to add that, as well as note all MWSE mods with an icon of sort so that they can be easily seen in the guide (and avoided if the user is not using the nightly build).

Sounds like a good idea to me. I would imagine that MWSE should be summarized in a short and puncy manner, so that people can get a basic understanding before reading more in depth.  I'd also imagine that you should especially stress that you read the documentation which is either a mod page and/or a readme. Because, people will try to skip reading if they can.
