### ISSUE TITLE
Jiub has vanilla face

### ISSUE THREAD

**Issue by Tyler799** [Tyler799/Morrowind-2019#5]
His left (visual right) eye is modded, but his face texture is the vanilla one as far as I can tell.

**Comment by yooksi** [comment]
@Tyler799 Have you found a solution to this problem yet?

**Comment by Tyler799** [comment]
Honestly I don't know if it's still occurring. Need to test on latest version of guide. Will comment again once I have.

**Comment by Tyler799** [comment]
Can confirm - it's still occurring.

**Comment by Tyler799** [comment]
This is what he looks like: https://imgur.com/8X1NTC0

Turns out I was wrong I guess, he's fine and that's how he's supposed to look.

**Comment by yooksi** [comment]
@Tyler799 That body texture though... Do we have a solution for that? Maybe some pack that is a bit more high texture, because it looks really bad in contrast with the head.

**Comment by Tyler799** [comment]
The body is much higher resolution than the head, and just doesn't match stylistically. However, Jiub is the worst of it. I don't think other NPCs have this problem. I'm definitely up for a solution if one exists.

**Comment by LexxCorp** [comment]
I have a copy of Westlys updated dark elf heads for his pluginless replacer. I can upload it if you want it. It might fix Jiubs vanilla esque face
