### ISSUE TITLE
Alternate (better?) Hlaalu Textures

### ISSUE THREAD

**Issue by DaelosTheCat** [Tyler799/Morrowind-2019#51]
Of all the Hlaalu retextures I've seen, this one offers the best visuals (imo). Makes the buildings look weathered and crisp. 

![HRT1](https://staticdelivery.nexusmods.com/mods/100/images/28061-5-1257526568.jpg)
![TRT3](https://staticdelivery.nexusmods.com/mods/100/images/28061-3-1257526568.jpg)

**Comment by Tyler799** [comment]
Only concern is that it isn't Atlas'd - which is a performance concern for some people. However, adding it as an alternate is certainly an option.

**Comment by DaelosTheCat** [comment]
What about this?
https://www.nexusmods.com/morrowind/mods/46022

**Comment by yooksi** [comment]
Looks good to me but it doesn't seem very vanilla friendly. The author guarantees good performance, and even though I haven't checked the texture/mesh size it does seem a bit beefy.

**Comment by Tyler799** [comment]
The textures are 1k x 1k, smaller than some of our other options. And if it's Atlased, I'm sure it's fine.

Whether stylistically it's a good choice is another matter. Not sure, haven't taken a super close look.

**Comment by Tyler799** [comment]
Added as alternate.

**Comment by yooksi** [comment]
This issue needs to be properly closed with a commit reference.
