### ISSUE TITLE
Animation Fix for Westly Heads

### ISSUE THREAD

**Issue by NullCascade** [Tyler799/Morrowind-2019#53]
https://www.dropbox.com/s/d70l2lbjvm0xloo/WestlyHeadsAnimFix.zip?dl=0

Fixes blinking and mouth movements with Westly's heads. [Source](https://discordapp.com/channels/210394599246659585/210394599246659585/568632192973144075).

**Comment by Tyler799** [comment]
Added. Thanks!

**Comment by yooksi** [comment]
This issue needs to be properly closed with a commit reference.

**Comment by NullCascade** [comment]
Was fixed in ab00d11e05ee656f75dce5684ae38cf7f115d37c.
