### ISSUE TITLE
Better Vivec-Velothi Retexture

### ISSUE THREAD

**Issue by DaelosTheCat** [Tyler799/Morrowind-2019#54]
I always prefer this retexture for VIvec-Velothi:
 https://www.nexusmods.com/morrowind/mods/32886/

It adds a layer of antiquity to interior textures that other mods don't imo. 

![Vivec-Velothi](https://staticdelivery.nexusmods.com/mods/100/images/32886-3-1278695953.jpg)

**Comment by Tyler799** [comment]
Added as alternate, thanks!

**Comment by yooksi** [comment]
This issue needs to be properly closed with a commit reference.
