### ISSUE TITLE
Connary's Fine Vials Typo

### ISSUE THREAD

**Issue by troygiorshev** [Tyler799/Morrowind-2019#58]
In the instructions for Connary's Fine Vials it states `disable tx_rustedmetal0`.  However this isn't the name of any of the textures.  There are, however, textures `tx_rustedmetal00` and `tx_rustedmetal10`.  (With the github font that's hard to see).  Does anyone know which file should be disabled?

**Comment by Tyler799** [comment]
That message is from well before I hopped onto the project. I'm going to go ahead and assume it was meant to be `tx_rustedmetal00` since that would make the most sense.

Thanks!
