### ISSUE TITLE
Recommend Typora to users

### ISSUE THREAD

**Issue by yooksi** [Tyler799/Morrowind-2019#62]
[Typora](https://typora.io/) should be our recommended Markdown viewer/editor. Users can view both the guide and changelog with it, as well as make fast and efficient edits before doing a PR. Did I mention the outliner that is used to quickly preview and navigate the TOC?

![2019-04-21_040520](https://user-images.githubusercontent.com/16436920/56464485-c29bd380-63ea-11e9-8727-d2ae72a6b625.png)

> What makes it different among countless markdown editors in this world is that: it basically doesn’t provide syntax highlighting for markdown source nor a separated view/window for previewing, instead, it combines syntax highlighting for markdown source and the live preview function in a single window seamlessly, thus make it possible for users to read and write acticles with markdown at the same time and in one window only

**Comment by Tyler799** [comment]
I think that this will end up being put into the CONTRIBUTING guide once it's done. For regular users, asking them to install something separate just to look at the guide might turn some off. However, for those editing it likely is appropriate. It seems like a good tool.
