### ISSUE TITLE
Move Correct UV Rocks above MOP

### ISSUE THREAD

**Issue by Tyler799** [Tyler799/Morrowind-2019#69]
This will be irrelevant once we swap to GH-LUA which has its own copy of Correct UV Rocks, but for now we should do this:

>It's highly recommended that you use this mod and install it BEFORE the optimization patch. It fixes a lot of bad UVs for rocks that aren't covered in my mod.

**Comment by yooksi** [comment]
I already looked into this matter when I was following the guide and there is no real conflict between *Correct UV Rocks* and MOP. Here is a WM conflict report:
```
= Lower ========================================
==1== Patch for Purists
Meshes\f\terrain_rock_ai_12.nif

= Higher ========================================
==81== WIP Smooth Correct UV Rocks
meshes\f\Terrain_cairn_AL_01.nif
meshes\f\Terrain_cairn_AL_02.nif
...
```

**Comment by Darkloke** [comment]
Hm, i have this one:

= Lower ========================================
==29== 06-06 Morrowind Optimization Patch
meshes\f\terrain_cairn_al_01.nif
meshes\f\terrain_cairn_al_02.nif
meshes\f\terrain_cairn_al_03.nif
meshes\f\terrain_cairn_ma_01.nif
meshes\f\terrain_cairn_ma_02.nif
meshes\f\terrain_cairn_ma_03.nif

**Comment by yooksi** [comment]
That's odd, I don't know why WM is not showing these files under conflicts. I might not fully understand how the installer package info categories, because I have those files you have listed under mismatched.

> - Mismatched: Files which are present in the data directory, but which aren't identical to the package's version of those files.
> - Conflicts: Shows which other packages will conflict the current package and for what files. Note that if a given file is mismatched, but the mismatch isn't due to other packages, then it won't appear. This report can be modified to show inactive conflicts and/or lower order conflicts through Package Header Commands.

**Comment by Darkloke** [comment]
Remiros said that "Correct UV Rocks and Smooth Correct UV Rocks should all be installed before MOP, as should most other fixes like Correct Meshes, PfP etc. Only Project Atlas should be installed afterwards. MOP doesn't cover rocks apart from those missing or broken in Correct UV Rocks."

**Comment by Darkloke** [comment]
I wonder if its also true for "Solstheim Tomb of the Snow Prince" since this mod also adds a lot of meshes.

**Comment by Tyler799** [comment]
Closed, irrelevant now that the guide uses MWSE.
