### ISSUE TITLE
Describe what the script/bat-file in Atlas textures do

### ISSUE THREAD

**Issue by Tyler799** [Tyler799/Morrowind-2019#71]
I don't know what they do, this is important and needs to be mentioned in the guide. Maybe have a dedicated section at the start of the guide (like where Bump Mapping is described) that explains how Atlas textures work.

**Comment by Darkloke** [comment]
Taken from ATL HLaalu readme for example:

If you use a Hlaalu texture replacer, you can use the "hlaalu_atlas_generator.bat" to patch the texture atlas with your replacer. You will need to have Image Magick (https://www.imagemagick.org/script/download.php) installed. Then move the .bat file into your "Textures" folder and run it. Be warned that it requires all textures to present as loose files and requires them to have the same relative proportions as vanilla:

So as i understand in case you are using Project Atlas and going to use certain texture replacers you need to setup ImageMagick, run bat-scripts and also check for correct aspect ration of textures. May be someone in community could suggest a ready receipt for that.

**Comment by Tyler799** [comment]
Oh, I see. It allows you to make things that aren't atlased into atlased textures.

I don't immediately see a point then. Many of the things in this guide are already Atlased, in fact most major things are. I think asking people to go into each mods texture folder and atlasing them seems a bit silly. 

I might consider it though.

**Comment by yooksi** [comment]
The Atlas batch files need to be re-run every time you add new custom textures, so that the ones that are compatible with Atlas operations could be atlased. This is taking full advantage of the Atlas installation.
