### ISSUE TITLE
Specify which BC mushrooms  option to take

### ISSUE THREAD

**Issue by Tyler799** [Tyler799/Morrowind-2019#72]
I forget what all the options are, I know one of them is glowing. I don't take that one. Need to list them out and actually tell people what to take.

**Comment by yooksi** [comment]
A new [version](https://github.com/Tyler799/Morrowind-2019/files/3103735/ATL_BC_Mushrooms.zip) of BC mushrooms Atlas is available:

- Fixed patchers for smoothed meshes and added resizer. 
- Added resizer to the standard patcher.
- Redid a folder structure to be clearer.
- Updated readmes (version number, installation instructions, changelog, install options for Image Magick, proportions for atlas and base files, mention of resizer).

**Comment by yooksi** [comment]
From Sataniel on #atlas Discord channel:
>If you use smoothed then you use "mushrooms only + fungus" and no normal "mushrooms"

**Comment by Tyler799** [comment]
Is that version you linked to from the nexus page, or somewhere else? 

Any thoughts on what to use? Is "smoothed" just a less-polygony mesh?

**Comment by yooksi** [comment]
@Tyler799 The version I linked comes from the #atlas discord channel but they should have updated the Nexus page by now, I know they were talking about doing it the same day they pinged me for this update. 

EDIT: It was uploaded to Nexus recently (*19 Apr 2019, 4:48PM*)

**Comment by yooksi** [comment]
> Any thoughts on what to use? Is "smoothed" just a less-polygony mesh?
It's the other way around, the smoothed version should contain a lot more polygons then the regular one since they need more triangles to make the mesh surface smooth.
