### ISSUE TITLE
Specify GITD is the "Glow in the Dahrk" patch for Project Atlas BC Mushrooms

### ISSUE THREAD

**Issue by Tyler799** [Tyler799/Morrowind-2019#73]
Currently this is unclear, needs to be cleaned up.

**Comment by Darkloke** [comment]
I would also add a note that after installation of this mod (GITD) u'll have a new option in main menu "mods config" (since its a MWSE mod) - just to clear the things, coz users can wonder "whats this and from where?".

**Comment by Tyler799** [comment]
I don't actually see any such patch in the BC Mushrooms mod.

**Comment by Tyler799** [comment]
However, Imperial and Velothi do have patches. Adding those now.
