### ISSUE TITLE
Clear up Main Menu / Splash screen replacers as being alternates

### ISSUE THREAD

**Issue by Tyler799** [Tyler799/Morrowind-2019#76]
Currently someone could get the impression you can take all of them at once. That's not right, they're all (I think?) alternates of each other. We need to clear that up.

**Comment by Darkloke** [comment]
Also add note that splash screens mods could replace each other in case they have similar filenames in format "splash_#counter" like Fresco Splash Screens and HD Concept-art Splash Screen and Main Menu do.
