### ISSUE TITLE
Mention "quick char" for testing

### ISSUE THREAD

**Issue by Tyler799** [Tyler799/Morrowind-2019#77]
This could be an extremely helpful tool for testing, but I didn't even know about it. Mentioning it early on in the guide would be good. Maybe at the end of Baseline installation and Boilerplate?

**Comment by yooksi** [comment]
This is the mod I use the purposes of testing:
https://www.nexusmods.com/morrowind/mods/27266

**Comment by Darkloke** [comment]
This is quick char:
http://www.fullrest.ru/files/quickchar-1c

This one is localized, but original may be somewhere too. Was in Hall of Fame on Planet Elder Scrolls btw.

**Comment by Tyler799** [comment]
Well we could add a "testing" section all of its own. Maybe include both of these as ways to test? Any recommendations on which?

I'd like to see some pros and cons of both.

**Comment by yooksi** [comment]
@Darkloke Could you find us a link to the unlocalized one and describe why that one is superior to the *Skip Tutorial* mod that I mentioned.

**Comment by Darkloke** [comment]
Probably this one:
http://mw.modhistory.com/download-44-7364

And i didnt say its in some way superior - just posted a link - its up to you to decide which one is better.

**Comment by LexxCorp** [comment]
This one is for testing:
http://mw.modhistory.com/download-17-12561

Places you in Seyda Neen with all skills/attributes set to 100 and A Daedric Long-sword giving you the best environment in which to play-test.

**Comment by LexxCorp** [comment]
+Adds a brand new Traveler's Ring (teleports to all cities and towns)

**Comment by LexxCorp** [comment]
[modTESTchargen_v2_5.zip](https://github.com/Tyler799/Morrowind-2019/files/3123406/modTESTchargen_v2_5.zip)
Here is the zip file since MMH can give some people issues
