### ISSUE TITLE
Add Better Barnacles mod

### ISSUE THREAD

**Issue by Tyler799** [Tyler799/Morrowind-2019#78]
Check for conflicts. If nothing already covers these textures, determine a position and add it.

https://www.nexusmods.com/morrowind/mods/43605/

**Comment by yooksi** [comment]
This looks good to me, nice addition.

**Comment by Darkloke** [comment]
No, no, guys - you didnt understand me a bit probably. Its ALREADY in the guide - right after "Underwater Static Replacer" in PLANTS Section.

I meant that i dont understand why its should be included, coz its provide 2 textures in 256x256 resolution vs 512x512 provided by MVP and Underwater Static Replacer.

**Comment by Tyler799** [comment]
Oh, you're correct. I'd like to see some side-by-side comparisons of the pictures, but 256x256 is pretty low. Added for removal, awaiting any further discussion.

**Comment by yooksi** [comment]
Agreed, I think we would need to see some comparison pictures before we remove it.

**Comment by Darkloke** [comment]
Here are they are:
https://imgur.com/a/Nqbtvux

**Comment by Tyler799** [comment]
After some back and forth, Better Barnacles, while strictly lower resolution, almost perfectly matches the vanilla style of them, while the other 2 are vast departures. I think the 2017 guide made the right call.
