### ISSUE TITLE
Contribution section and license

### ISSUE THREAD

**Issue by owlnical** [Tyler799/Morrowind-2019#8]
Now that this is turning in to a larger project which really encourages contributions (and hopefully something which continues to improve way beyond 2019!), should it be put under some kind of license? E.g. under [cc-by-sa 4.0](https://creativecommons.org/licenses/by-sa/4.0/)?

Perhaps a `## contributors` section as well? IMO always nice to see your name somewhere in projects, and I *think* others feel the same way :) and that would be a good place to add the authors of the old guides as well.

**Comment by Tyler799** [comment]
Rough draft of ## Contributors section is added in.

**Comment by owlnical** [comment]
I only have minor experience with CC honestly, but I think it's a good idea. It's like a formal statement that this project is open for everyone. But it's not mandatory or anything.

I usually add something like this at the end of the file (depending on what licensed is used ofc):

```
This work is licensed under the Creative Commons Attribution-ShareAlike 4.0 International License. To view a copy of this license, visit http://creativecommons.org/licenses/by-sa/4.0/ or send a letter to Creative Commons, PO Box 1866, Mountain View, CA 94042, USA.
```

But imo just something like "licensed under CC BY-SA 4.0 + link is good enough.

**Comment by Tyler799** [comment]
Added a license to the end. Thanks!

**Comment by owlnical** [comment]
No problem, happy to help out where I can :)

**Comment by yooksi** [comment]
The repository should be properly licensed with a LICENSE file:
https://help.github.com/en/articles/licensing-a-repository

I recommend using the Creative Commons Zero v1.0 Universal license:
> The Creative Commons CC0 Public Domain Dedication waives copyright interest in a work you've created and dedicates it to the world-wide public domain. Use CC0 to opt out of copyright entirely and ensure your work has the widest reach. As with the Unlicense and typical software licenses, CC0 disclaims warranties. CC0 is very similar to the Unlicense.

**Comment by Tyler799** [comment]
I've gone ahead and made a license file and moved the license into it. I'd rather stick with the license we have however.

This:

>You must give appropriate credit, provide a link to the license, and indicate if changes were made

Is important to me. I'm fine with people doing whatever they want, but for a lot of reasons I feel this is appropriate and the CC0 doesn't include that.
