### ISSUE TITLE
Daedric Lord Armor Face of God

### ISSUE THREAD

**Issue by LexxCorp** [Tyler799/Morrowind-2019#83]
I have noticed that we have Daedric Lord Armor Morrowind Edition in the Armor section of the guide, however, we do not have Daedric Lord Armor Face of God that adds the helmet that was missed in Daedric Lord Armor Morrowind Edition

**Comment by LexxCorp** [comment]
Here's the link >>https://www.nexusmods.com/morrowind/mods/45037

**Comment by Soulslayer116** [comment]
Hey, here's a version of daedric face of gods matching with daedric lord armor by saint bahamut.

https://www.nexusmods.com/morrowind/mods/45037/

Some people complained that the meshe had minor issues, specially on Openmw. My experience is on a normal installation, and I got no problems.
