### ISSUE TITLE
RR Mod Series - Better Meshes

### ISSUE THREAD

**Issue by Darkloke** [Tyler799/Morrowind-2019#87]
"Before installing, disable meshes/m/misc_com_pillow_01."

Whats the real reason for this? I have asked mod's author and he said there should be no problems with this mesh.

Also mod page contains two additional fixes:
Fix for misc_com_metal_plate_05
Fix for misc_dwrv_artifact60

**Comment by Tyler799** [comment]
The disabling is something from the original 2017 guide. It looks like Better Meshes Plus Optimization also provides that mesh, but is loaded *before* RR Beter Meshes.

So it's likely that the author of the guide liked the one from BMPO better than RR.

However, if you'd like to open them up and compare them side-by-side, I'd considering swapping it.

As for the fixes, those should definitely be downloaded and loaded right after. Those just came after the 2017 guide.

When I get some free time (very little right now, finals week) I'll go ahead and put those fixes in.
