### ISSUE TITLE
Table of Contents?

### ISSUE THREAD

**Issue by owlnical** [Tyler799/Morrowind-2019#9]
For longer docs this I find a table of contents to be really useful. This is also something which is supported in GFM syntax (inlcluding [spaces](https://gist.github.com/jonschlinkert/ac5d8122bfaaa394f896)).

What do you think about a TOC? Will others find it useful? Is it worth the effort? I mean it would need to be updated every time a header is added or changed/moved, which kinda is a pain... it seems like it can be automated with [this](https://github.com/ekalinin/github-markdown-toc) though.

**Comment by Tyler799** [comment]
I don't mind handling it manually. I think that the number of sections won't change a *ton* into the future, and even if it does it shouldn't be too tedious. I'll prob avoid using any other tools for now to avoid a mess. 

In any case, I'll be away from my computer for the next 2.5 hours or so. If you want to work on it that's fine, if not I'll take care of it once I'm back.

**Comment by owlnical** [comment]
Cool, I'll have a go at it.

-------- Original Message --------
