### ISSUE TITLE
base files

### ISSUE THREAD

**Issue by Darkloke** [Tyler799/Morrowind-2019#91]
Probably not an issue, but more like a question/research.

Morrowind installation have a lot of basic game files that not packed in bsa, but lie directly in data files folders: video, music, sounds, some meshes, textures, icons, etc.

Is it possible to pack all this files in bsa-archives to have a "clean installation", so we would have all basic games files in archives and data files folders would contain only a mod files.

**Comment by Darkloke** [comment]
Ah, dont bother. I spoke with Hrnchamd and he said its impossible so far.

**Comment by Tyler799** [comment]
I don't see how a BSA would matter here. With MO2, the data files folder remains completely clean with regards to normal mods. With Wrye it technically doesn't, but it also keeps track of all changes it makes so it can revert them. Does a great job of it too.
