### ISSUE TITLE
Connary's Fine Vials 

### ISSUE THREAD

**Issue by Darkloke** [Tyler799/Morrowind-2019#98]
I would add a note that the player could skip installing icons, since the ones from ultimate icons could be better (or a matter of taste) - or at least they kept in the same style.

And regarding metal textures - one (better) version comes from Full Dwemer Retexture and the other one - from Papill6n various graphics things.

**Comment by Tyler799** [comment]
>And regarding metal textures - one (better) version comes from Full Dwemer Retexture and the other one - from Papill6n various graphics things.

Yes, I realize that. Currently in the guide both of those are before this mod. I'm not sure what you're suggesting I do here.
